{% set name = "caf.ntem" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/caf_ntem-{{ version }}.tar.gz
  sha256: 81e0e816859b96a1c0bfc765f575a647f979719ed1ec2ab06fcb7fb8448438de

build:
  entry_points:
    - caf.ntem = caf.ntem.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - pandas >=2.2.3
    - tqdm >=4.67.1
    - caf.toolkit >=0.9.0
    - sqlalchemy >=2.0.37
    - caf.base >=0.2.0

test:
  imports:
    - caf
  commands:
    - pip check
    - caf.ntem --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/transport-for-the-north/caf.ntem
  summary: CAF package for extracting and analysing NTEM data.
  dev_url: https://github.com/transport-for-the-north/caf.ntem
  doc_url: https://cafntem.readthedocs.io/en/stable/
  license: LicenseRef-TfN-License
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MattBuckley-TfN
    - BenTaylor-TfN
    - isaac-tfn
    - Kieran-Fishwick-TfN
